=== mmbase/speeltuin/applications/packaging/src/org/mmbase/applications/packaging/resources/providers_1_0.dtd
<!--
    providers.dtd
-->

<!ELEMENT providers (provider*)>

<!ELEMENT provider (path,account*,password*,description*)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT account (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST provider name CDATA #IMPLIED>
<!ATTLIST provider maintainer CDATA #IMPLIED>
<!ATTLIST provider method CDATA #IMPLIED>

=== mmbase/speeltuin/applications/packaging/config/packaging/providers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE providers PUBLIC "-//MMBase/DTD providers config 1.0//EN" "http://www.mmbase.org/dtd/providers_1_0.dtd">
<providers>
	<provider name="Submarine Package Server" maintainer="Submarine" method="http" >
		<path>http://packages.submarine.nl/mmbase/mmpm/sharing/sharedpackages.jsp</path>
		<account>guest</account>
		<password>guest</password>
		<description></description>
	</provider>
	<provider name="import dir" maintainer="local" method="disk" >
		<path>~import</path>
		<description>webapp import dir</description>
	</provider>
        <provider name="build dir" maintainer="local" method="disk" >
                <path>~build</path>
                <description>webapp build dir</description>
        </provider>
</providers>
