=== mmbase/speeltuin/applications/functions/src/org/mmbase/util/functions/resources/functionset_1_0.dtd
<!--
    functionset.dtd
-->

<!ELEMENT functionset (status,version,description,function*)>

<!ELEMENT status (#PCDATA)>
<!ELEMENT version (#PCDATA)>

<!ELEMENT function (description,type,class,method,param*,return)>
<!ATTLIST function name CDATA #IMPLIED>

<!ELEMENT description (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT class (#PCDATA)>

<!ELEMENT method (#PCDATA)>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #IMPLIED>
<!ATTLIST param type CDATA #IMPLIED>
<!ATTLIST param description CDATA #IMPLIED>

<!ELEMENT return (field*)>
<!ATTLIST return type CDATA #IMPLIED>

<!ELEMENT field (#PCDATA)>
<!ATTLIST field name CDATA #IMPLIED>
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field description CDATA #IMPLIED>

=== mmbase/speeltuin/andre/xml2pdf/config/functions/xml2pdf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE functionset PUBLIC "//MMBase - functionset //" "http://www.mmbase.org/dtd/functionset_1_0.dtd">
<functionset>
<version>1</version>
<description>Functionset to create a PDF from a webpage.</description>
  
  <function name="xml2pdf">
    <description>Creates an attachments node containing a PDF from a xml.</description>
    <type>class</type>
    <class>org.mmbase.applications.xml2pdf.XML2PDFnode</class>
    <method>createPDFnode</method>
    <param name="cloud" type="org.mmbase.bridge.Cloud" description="MMBase cloud" />
	<param name="xml"   type="String" description="The xml or xhtml use, has to be a complete url" />
	<param name="xsl"   type="String" description="A xhtml2pdf XSL (FO) file to transform the xhtml to fo which FOP can use (has to live in MMBase its config/xsl directory)." />
    <param name="title" type="String" description="Title of the resulting attachments node" />
    <return type="Node" />
  </function>
  
</functionset>

=== mmbase/speeltuin/andre/friendlylink/config/functions/friendlylinks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE functionset PUBLIC "//MMBase - functionset //" "http://www.mmbase.org/dtd/functionset_1_0.dtd">
<functionset>
<version>1</version>
<description>friendlylinks and related functions</description>
  
  <function name="friendlylink">
		<description>create a nice url to a page</description>
		<type>class</type>
		<class>org.mmbase.applications.friendlylink.PagesFunctions</class>
		<method>convertToFriendlyLink</method>
		<param name="cloud"   type="org.mmbase.bridge.Cloud" description="MMBase cloud" />
		<param name="request" type="javax.servlet.http.HttpServletRequest" description="HTTP request" />
		<param name="page"    type="Node"    description="A pages node" />
		<param name="convert" type="Boolean" description="You might not want to, f.e. when testing">true</param>
		<return type="String" /> 
  </function>

  <function name="flarticles">
		<description>create a nice url to an article on a page</description>
		<type>class</type>
		<class>org.mmbase.applications.friendlylink.ArticlesFunctions</class>
		<method>convertToFriendlyLink</method>
		<param name="cloud" type="org.mmbase.bridge.Cloud" description="MMBase cloud" />
		<param name="request" type="javax.servlet.http.HttpServletRequest" description="HTTP request" />
		<param name="page" type="String" description="Nodenumber of a pages node" />
		<param name="art" type="String" description="Nodenumber of the article" />
		<param name="convert" type="Boolean" description="You might not want to, f.e. when testing">true</param>
		<return type="String" /> 
  </function>

  <function name="pagestoroot">
		<description>List the nodenumbers of pages forming a path to the root of the site.
			#listPagesToRoot(org.mmbase.bridge.Node page)</description>
		<type>class</type>
		<class>org.mmbase.applications.friendlylink.PagesFunctions</class>
		<method>listPagesToRoot</method>
		<param name="page" type="Node" description="A pages node" />
		<return type="java.util.List" /> 
  </function>
  
  <function name="showcache">
		<description>A utility or admin function to show all cache entries.</description>
		<type>class</type>
		<class>org.mmbase.applications.friendlylink.UrlConverter</class>
		<method>showCache</method>
		<return type="String" /> 
  </function>

</functionset>
